name: Unit test and Release

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        php-versions: [ '7.2', '7.4' ]
        wp-versions: [ '5.8', 'trunk' ]
    name: PHP ${{ matrix.php-versions }} / WP ${{ matrix.wp-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl #optional, setup extensions
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver

      - name: Check PHP Version
        run: php -v

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: npm install
        run: npm ci

      - name: Build
        run: |
          bash ./bin/build.sh

      - name: Install WordPress
        run: |
          chmod -R 767 ./ # TODO: Possibly integrate in wp-env
          npm run wp-env start

      - name: Running lint check
        run: npm run lint-php

      - name: Running single site unit tests
        run: npm run test-unit-php
        if: ${{ success() || failure() }}
